apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: carbon-bot
resources:
- deployment.yaml
- namespace.yaml
- secret.yaml
images:
- name: spt-frontend-image
  newName: public.ecr.aws/b9e2c7d9/carbon-discord
  newTag: e5a9a3c
