---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: carbon-bot-env
  namespace: carbon-bot
spec:
  encryptedData:
    env: AgCyBramyDTSd7eaPht7UxdEn4TwAlS5jOX5Lde1TCRdpY7Oi32PS61NiGmoFspkGlKXrKjE8MT0kdMooO9V2Onsx65RVJovsaft3st/fxeO5+Sqety5dSt301i2bW0zjS3mo/ZLL8GYQFR0i5c1woT5KeMP72eQgxz97ffVygKIvUDpertN0an0o2qVlMd3WHGFrcjdP/3zViMoF5jxjd6tCBUKUUQUCso8jcBQ1K30WmOUcdG5cCLBALQt1lAaL9krQ2qP0MYfPh1e9j81neQ6//jshudAH/j6R0iveahTZNk2DqBZPunGfwyGW0tSsaaeN1ywX1uh7YS/w14Ox+h30vTiZERY8net+d7f9s1NTLP+iuhuZL/ft3ZCkXJCxr+Pz4v1ElepsLAy7GAJaEo2XmlXqXc3QsUINYmbRuTv0Hx4VmCfHM9dO8kR94gh/CGfPJ5hoA+Puzg9asZ45y3fcSIUtSRu7XPC8Xp3ORAPwyUQAcbqiBRnv5ZCrhr/Ynw2Gn3TjLPpQi8fQ/nS89k4C2CEoQ2MfLi7T5w4XpWexajmgFrTFra94vJbwEjwlqFr21G6BUUI6H2ton6Hie1u2hzrahokYU+nJPRnDqiOSFrh64gPoTolg3JUkwtVO1OE0ffPKkD9xBuycg/uXn56IRxGz3VIkxWTkinRS15io1aG2V19Yc0qASX8ooDtrGyCh3jM8W7PD8vtRaA+MvdLVU1TnyPb+kbI3ATv8pp2gsSXeUcA0OB1banPC5Ot9e4duywlat8UBSI69h3KcsKrOqPNvX+Ytt+3SvjIaO8g2DOt4rKWo9S3P9vHl3AAZv/gkk+EE9NUXvIMXzz1auisbrTPbW/qeKTRzLBSBIWoOrGlxpAhAUG5jAwoGI7kNIFyH/BWNgNvTw8Lj1c=
  template:
    metadata:
      name: carbon-bot-env
      namespace: carbon-bot