---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: carbon-bot-env
  namespace: carbon-bot
spec:
  encryptedData:
    env: AgB4e/7+iqU4jriHQWXuOS/ORDYJ87WjgS5WI8j7xTQNJBYG4tdTmt6O0wJtLu5S4k9NfdeiYt9LSyrNuipa+OoOE23D3eMuEXVy1AzD4+XNKgsCivVWGYqpoitZ0Fbyq5ZIsb23sXMhI/BzwgU/+y22LMZrwXgspv9xI33PHIMLabF2GAIMR1MZOzlQJbmCpejLAdrtay2Kar3gRESxWP6sdU0dHXQJ6qWKkqofMpJrbgzJMVcYjbGbIWhIyjvzQHqaWxtnAEEQCYmgSrGZffOIxgZrljRN3INJlLNkvH8DhDa2k2eR4rCIToOhBfFJgDkWA2rtiWue4s+2EaIWKkkaDLiPsK0KWwitwqrzmmE+G3+Q8AIdKFBbm5x5PyScQ14bemZHzWQXhmV6grXPQBNiZr37PfPszEMbzEBThMZ34L2BurGAnYdvBgIc2Bz8R/jfo+YRQht+f3dLBCSyuwVWY3gqoJOlDWzaSlsz80w9Pm+LADv6WhU24ZHkGIggfMKiPmSVIe/KwDYCSr2Q4lkSHpzW60WNeI4LMSO+cwet5My+aeSmi554KCcDkIDalE/X0JdqjlYVTu/SyumjDugZncPMlLHd3fA26ccdIyqaUny7UAmZ/WatuQE5PjGRigp0B0JpOPb7IsalNqPMwxX5zOoi8Qh0U9QnDinvkb0fL9FHlvj8Ejc1QOI+ro+10lnC6U5KktDyY/r6ICgW8+NwnQ0DljSOt5pOeKDf1Ppdtr2Cqjq7Dh8EyiB7FbpLQIuIibrcR2NIGwfyoPOpfURwfv9afn1PiRv3BeYohdMapsNyoekQtPg2TqDxQxHYkJfJmyJ5/3WRUs7eq+XRQPZfsv8DB6iGNgk+G2hh+nfmFUAJTr2dVrP6YvtaT9VnPFiEfY7FowSuZGD5Ohw=
  template:
    metadata:
      name: carbon-bot-env
      namespace: carbon-bot