name: Build and deploy the bot
on:
  push:
    branches: ["main", "*-ci-test"]
env:
  ECR_REPO: "public.ecr.aws/b9e2c7d9/carbon-discord"
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      imgTag: ${{ steps.calc_tag.outputs.tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Calc tag
        id: calc_tag
        run: |
          short_hash="$(git rev-parse --short HEAD)"
          echo "tag=${short_hash}" | tee $GITHUB_OUTPUT
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::609805986527:role/carbon-bot-ci"
          aws-region: us-east-1
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          TAG: ${{ steps.calc_tag.outputs.tag }}
        run: |
          docker build -t $ECR_REPO:$TAG .
          docker push $ECR_REPO:$TAG
  # bump_tag:
  #   name: Bump FE kustomization tags
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     contents: write
  #   concurrency:
  #     group: bump-tag
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2
  #     - name: Update BE k8s tag
  #       run: |
  #         cd infra/overlays/prod
  #         TAG="${{ needs.build.outputs.imgTag }}"
  #         git pull
  #         kustomize edit set image "spt-frontend-image=$ECR_REPO:$TAG"
  #         git config --global user.name 'Github actions'
  #         git config --global user.email 'githubaction@spotpricetracker.com'
  #         git add ./kustomization.yaml
  #         git commit -m "Release FE version $TAG"
  #         git push
